/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xb.h"

//#define RCC_APB2ENR *(volatile unsigned int *)(0x40021000 + 0x18)

int main(void)
{
	RCC->APB2ENR |= 1 << 4; // Enable GPIOC

	// Set PC13 as push-pull output at 2MHz
	GPIOC->CRH &= ~(1 << 20 | 1 << 21); // MODE13 = 00
	GPIOC->CRH |= 1 << 21; // MODE13 = 10 (Output at 2MHz)
	GPIOC->CRH &= ~(1 << 22 | 1 << 23); // CNF13 = 00 (Push-pull)

	// PC13 = 1
	GPIOC->ODR |= 1 << 13; // This does not turn on the led on the bluepill board because it is low-active

	/* Loop forever */
	while(1)
	{
	}
}
